version: "3.9"

services:
  fdaapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fdaapi_prod 
    ports:
      - "7097:8080" 
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Production
      # *** Reverse Proxy Configuration ***
      # Running behind HTTPS/HTTP proxy.
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__MyDB: ${ConnectionStrings__MyDB}
    restart: unless-stopped